### ISSUE TITLE
$arguments don't work, as you would expect

### ISSUE THREAD

**Issue by Jocadbz** [KitsuneSemCalda/Fox-Shell#1]
I don't know if it's really possible to do this with Golang, but just for records:
### Issue
Using $ arguments don't work
### Steps to reproduce
- Run echo $PATH
- See that this returns only "$PATH", not what it should do.
### Expected behavior
- "echo $PATH" should return the files where the commands are currently being read.

**Comment by KitsuneSemCalda** [comment]
In this recent commit we fixed the $arguments problem, if you can test the update

**Comment by Jocadbz** [comment]
Well, looks like it's fixed with commit 05216c5 . Gonna close this issue.
